# Generated by Django 3.2.7 on 2021-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App01s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=255, verbose_name='工作名称')),
                ('job_type', models.CharField(blank=True, max_length=255, verbose_name='工作类型')),
                ('job_city', models.IntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳'), (3, '杭州')], default=0, verbose_name='工作地点')),
                ('job_email', models.EmailField(max_length=255, verbose_name='投递邮箱')),
            ],
        ),
    ]
