# Generated by Django 3.2.7 on 2021-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='create_time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='创建时间'),
        ),
    ]
