# Generated by Django 3.2.7 on 2021-09-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_app01s_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app01s',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
