# Generated by Django 3.2.7 on 2021-09-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_app01s_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app01s',
            name='create_time',
        ),
    ]
