# Generated by Django 3.2.7 on 2021-09-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_app01s_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='job_test1',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试1'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test10',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试10'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test2',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试2'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test3',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试3'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test4',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试4'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test5',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试5'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test6',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试6'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test7',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试7'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test8',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试8'),
        ),
        migrations.AddField(
            model_name='app01s',
            name='job_test9',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试9'),
        ),
    ]
