# Generated by Django 3.2.7 on 2021-09-23 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210923_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
