# Generated by Django 3.2.7 on 2021-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_app01s_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='job_position',
            field=models.TextField(blank=True, max_length=1024, verbose_name='岗位职责'),
        ),
    ]
