# Generated by Django 3.2.7 on 2021-09-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_app01s_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='job_attachment',
            field=models.FileField(blank=True, upload_to=None, verbose_name='其他附件'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='job_name',
            field=models.CharField(max_length=255, verbose_name='工作名称'),
        ),
    ]
