# Generated by Django 3.2.7 on 2021-09-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_app01s_job_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
