# Generated by Django 3.2.7 on 2021-09-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_app01s_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='job_img',
            field=models.ImageField(default=None, height_field=200, upload_to='photo', verbose_name='附加图片'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='job_attachment',
            field=models.FileField(blank=True, upload_to='attachment/%Y%m%d/', verbose_name='其他附件'),
        ),
    ]
