# Generated by Django 3.2.7 on 2021-09-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20210928_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app01s',
            name='job_attachment',
            field=models.FileField(upload_to='attachment/%Y%m%d/', verbose_name='其他附件'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='job_img',
            field=models.ImageField(height_field=200, upload_to='photo', verbose_name='附加图片'),
        ),
    ]
