# Generated by Django 3.2.7 on 2021-09-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20210928_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app01s',
            name='job_img',
        ),
    ]
