# Generated by Django 3.2.7 on 2021-09-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_app01s_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='app01s',
            name='job_img',
            field=models.ImageField(default=None, upload_to='photo', verbose_name='附加图片'),
        ),
    ]
