# Generated by Django 3.2.7 on 2021-09-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_app01s_job_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app01s',
            name='job_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='工作名称'),
        ),
    ]
