# Generated by Django 3.2.7 on 2021-09-28 07:05

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_app01s_job_name'),
    ]

    operations = [
    ]
