# Generated by Django 3.2.7 on 2021-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20210928_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app01s',
            name='job_attachment',
            field=models.FileField(default=None, upload_to='attachment/%Y%m%d/', verbose_name='其他附件'),
        ),
    ]
