# Generated by Django 3.2.7 on 2021-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_app01s_job_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app01s',
            name='create_time',
            field=models.DateTimeField(default=None, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='job_attachment',
            field=models.FileField(upload_to='attachment/%Y%m%d/', verbose_name='其他附件'),
        ),
    ]
