# Generated by Django 3.2.7 on 2021-10-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20210928_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('phone', models.IntegerField(max_length=32, verbose_name='手机号')),
            ],
        ),
        migrations.AlterModelOptions(
            name='app01s',
            options={'verbose_name': '招聘', 'verbose_name_plural': '招聘'},
        ),
    ]
