# Generated by Django 3.2.7 on 2021-10-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
    ]
