# Generated by Django 3.2.7 on 2021-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_users_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_title', models.CharField(max_length=255, verbose_name='说说标题')),
                ('talk_context', models.TextField(max_length=1024, verbose_name='说说内容')),
                ('create_time', models.DateTimeField(default=None, verbose_name='创建时间')),
            ],
        ),
    ]
