# Generated by Django 3.2.7 on 2021-10-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_talks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='talk_context',
            field=models.TextField(max_length=2048, verbose_name='说说内容'),
        ),
    ]
