# Generated by Django 3.2.7 on 2021-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_alter_talks_talk_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talks',
            options={'verbose_name': '说说', 'verbose_name_plural': '说说'},
        ),
        migrations.AddField(
            model_name='talks',
            name='talk_other1',
            field=models.CharField(default=None, max_length=255, verbose_name='其他内容'),
        ),
    ]
