# Generated by Django 3.2.7 on 2021-10-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_auto_20211012_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talks',
            name='talk_other1',
        ),
    ]
