# Generated by Django 3.2.7 on 2021-10-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_remove_talks_talk_other1'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.users'),
        ),
    ]
