# Generated by Django 3.2.7 on 2021-10-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_alter_talks_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='creator',
            field=models.CharField(default=None, max_length=255, verbose_name='说说创建者'),
        ),
    ]
