# Generated by Django 3.2.7 on 2021-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_alter_talks_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(blank=True, max_length=255, verbose_name='商品名称')),
                ('commodity_price', models.IntegerField(blank=True, max_length=255, verbose_name='商品价格')),
                ('commodity_type', models.IntegerField(blank=True, choices=[(0, '食品'), (1, '服饰'), (2, '电子产品'), (3, '百货')], default=None, max_length=255, verbose_name='商品类型')),
                ('create_time', models.DateTimeField(default=None, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
