# Generated by Django 3.2.7 on 2021-10-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_auto_20211014_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='commodity_type',
        ),
    ]
