# Generated by Django 3.2.7 on 2021-10-14 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_shoptypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='commodity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.shoptypes'),
        ),
    ]
