# Generated by Django 3.2.7 on 2021-10-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_auto_20211014_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='app01',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.shoptypes'),
        ),
    ]
