# Generated by Django 3.2.7 on 2021-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0040_auto_20211014_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='commodity_img',
            field=models.ImageField(default=None, upload_to='photo', verbose_name='商品图片'),
        ),
    ]
