# Generated by Django 3.2.7 on 2021-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0041_shops_commodity_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '说说用户', 'verbose_name_plural': '说说用户'},
        ),
        migrations.AddField(
            model_name='shops',
            name='commodity_num',
            field=models.IntegerField(default=None, max_length=10, verbose_name='商品库存'),
        ),
        migrations.AddField(
            model_name='shops',
            name='commodity_presentation',
            field=models.CharField(default=None, max_length=2048, verbose_name='商品描述'),
        ),
    ]
