# Generated by Django 3.2.7 on 2021-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0043_auto_20211015_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporders',
            name='buy_commodity_num',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='购买商品数量'),
        ),
        migrations.AlterField(
            model_name='shoporders',
            name='buy_total_price',
            field=models.FloatField(blank=True, max_length=255, verbose_name='购买商品总价'),
        ),
        migrations.AlterField(
            model_name='shoporders',
            name='commodity_price',
            field=models.FloatField(blank=True, max_length=255, verbose_name='商品单价'),
        ),
    ]
