# Generated by Django 3.2.7 on 2021-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0044_auto_20211015_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporders',
            name='buy_commodity_num',
            field=models.IntegerField(blank=True, verbose_name='购买商品数量'),
        ),
    ]
