# Generated by Django 3.2.7 on 2021-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0045_alter_shoporders_buy_commodity_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='commodity_num',
            field=models.IntegerField(default=None, verbose_name='商品库存'),
        ),
    ]
