# Generated by Django 3.2.7 on 2021-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0046_alter_shops_commodity_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporders',
            name='buy_time',
            field=models.DateTimeField(default=None, verbose_name='创建时间'),
        ),
    ]
