# Generated by Django 3.2.7 on 2021-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0047_shoporders_buy_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoporders',
            options={'verbose_name': '商品订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AddField(
            model_name='shoporders',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='订单编号'),
        ),
    ]
