# Generated by Django 3.2.7 on 2021-10-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0048_auto_20211015_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporders',
            name='buy_time',
            field=models.CharField(default=None, max_length=255, verbose_name='创建时间'),
        ),
    ]
