# Generated by Django 3.2.7 on 2021-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0050_zhanyong'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=255, verbose_name='会议室名称')),
            ],
        ),
        migrations.DeleteModel(
            name='ZhanYong',
        ),
    ]
