# Generated by Django 3.2.7 on 2021-10-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0051_auto_20211019_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField(default=None, verbose_name='使用日期')),
                ('begin_time', models.TimeField(default=None, verbose_name='开始时间')),
                ('end_time', models.TimeField(default=None, verbose_name='结束时间')),
                ('meeting_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.meetingroom', verbose_name='会议室名称')),
            ],
        ),
    ]
