# Generated by Django 3.2.7 on 2021-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0052_meetingroominfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'verbose_name': '会议室管理', 'verbose_name_plural': '会议室管理'},
        ),
        migrations.AlterModelOptions(
            name='meetingroominfo',
            options={'verbose_name': '会议室预定管理', 'verbose_name_plural': '会议室预定管理'},
        ),
        migrations.AddField(
            model_name='meetingroominfo',
            name='time_id',
            field=models.IntegerField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00'), (14, '21:00'), (15, '22:00'), (16, '23:00')], default=0),
        ),
    ]
