# Generated by Django 3.2.7 on 2021-10-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0053_auto_20211020_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='meeting_room_num',
            field=models.IntegerField(default=0, verbose_name='承受人数'),
        ),
        migrations.AlterField(
            model_name='meetingroominfo',
            name='time_id',
            field=models.IntegerField(choices=[(1, '9:00'), (2, '9:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '14:00'), (9, '14:30'), (10, '15:00'), (11, '15:30'), (12, '16:00'), (13, '16:30'), (14, '17:00'), (15, '17:30'), (16, '18:00'), (17, '18:30'), (18, '19:00')], default=0),
        ),
    ]
