# Generated by Django 3.2.7 on 2021-10-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0057_meetingroominfo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='', max_length=255, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
