# Generated by Django 3.2.7 on 2021-10-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0058_users_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroominfo',
            name='room_use',
            field=models.CharField(default='', max_length=255, verbose_name='使用者'),
            preserve_default=False,
        ),
    ]
