# Generated by Django 3.2.7 on 2021-10-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0060_remove_meetingroominfo_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroominfo',
            name='begin_time',
            field=models.IntegerField(choices=[(1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '14:00'), (9, '14:30'), (10, '15:00'), (11, '15:30'), (12, '16:00'), (13, '16:30'), (14, '17:00'), (15, '17:30'), (16, '18:00'), (17, '18:30'), (18, '19:00')], default=0),
        ),
        migrations.AlterField(
            model_name='meetingroominfo',
            name='end_time',
            field=models.IntegerField(choices=[(1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '14:00'), (9, '14:30'), (10, '15:00'), (11, '15:30'), (12, '16:00'), (13, '16:30'), (14, '17:00'), (15, '17:30'), (16, '18:00'), (17, '18:30'), (18, '19:00')], default=0),
        ),
        migrations.AlterField(
            model_name='meetingroominfo',
            name='room_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.users', verbose_name='使用者'),
        ),
    ]
