# Generated by Django 3.2.7 on 2021-10-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0061_auto_20211021_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverTimeOrLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(max_length=255, verbose_name='申请编号')),
                ('apply_type', models.IntegerField(choices=[(0, '加班'), (0, '调休')], verbose_name='申请类型')),
                ('apply_title', models.CharField(max_length=255, verbose_name='申请单标题')),
                ('apply_reason', models.CharField(max_length=255, verbose_name='申请理由')),
                ('begin_time', models.CharField(max_length=255, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=255, verbose_name='结束时间')),
                ('time_length', models.CharField(max_length=255, verbose_name='时长')),
                ('approver', models.CharField(max_length=255, verbose_name='审批人')),
                ('apply_status', models.CharField(max_length=255, verbose_name='审批状态')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.users', verbose_name='申请人')),
            ],
        ),
    ]
