# Generated by Django 3.2.7 on 2021-10-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0063_auto_20211022_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeorleave',
            name='apply_reason',
            field=models.TextField(max_length=2048, verbose_name='申请理由'),
        ),
        migrations.AlterField(
            model_name='overtimeorleave',
            name='begin_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='overtimeorleave',
            name='end_time',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='overtimeorleave',
            name='time_length',
            field=models.IntegerField(max_length=11, verbose_name='时长'),
        ),
    ]
