# Generated by Django 3.2.7 on 2021-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0064_auto_20211022_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeorleave',
            name='time_length',
            field=models.IntegerField(verbose_name='时长(h)'),
        ),
    ]
