# Generated by Django 3.2.7 on 2021-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0065_alter_overtimeorleave_time_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeorleave',
            name='approver_opinion',
            field=models.TextField(default='', max_length=2048, verbose_name='审批意见'),
            preserve_default=False,
        ),
    ]
