# Generated by Django 3.2.7 on 2021-10-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0067_auto_20211026_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.role'),
        ),
    ]
