# Generated by Django 3.2.7 on 2021-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0069_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name2',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
