# Generated by Django 3.2.7 on 2021-11-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0071_remove_book_book_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('context', models.TextField(max_length=4096, verbose_name='内容')),
                ('type', models.CharField(max_length=255, verbose_name='类型')),
                ('creator', models.CharField(max_length=255, verbose_name='作者')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
