# Generated by Django 3.2.7 on 2021-11-08 06:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0072_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='context',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='内容'),
        ),
    ]
