# Generated by Django 3.2.7 on 2021-11-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0075_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='context',
        ),
    ]
