# Generated by Django 3.2.7 on 2021-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0076_remove_blog_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='label',
            field=models.CharField(default='', max_length=255, verbose_name='标签'),
            preserve_default=False,
        ),
    ]
