# Generated by Django 3.2.7 on 2021-11-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0077_blog_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('0', 'python基础'), ('1', 'Django框架'), ('2', 'Flask框架'), ('3', 'mysql'), ('4', 'linux常用命令')], max_length=255, verbose_name='类型'),
        ),
    ]
