# Generated by Django 3.2.7 on 2021-11-10 02:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0078_alter_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='context',
            field=tinymce.models.HTMLField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='标签'),
        ),
    ]
