# Generated by Django 3.2.7 on 2021-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0079_auto_20211110_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
