# Generated by Django 3.2.7 on 2021-11-19 10:14

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0082_auto_20211111_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='create_date',
            field=models.DateField(blank=True, default=None, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='create_time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='job_attachment',
            field=models.FileField(blank=True, upload_to='attachment/%Y%m%d/', verbose_name='其他附件'),
        ),
        migrations.AlterField(
            model_name='app01s',
            name='job_img',
            field=models.ImageField(blank=True, default=None, upload_to='photo', verbose_name='附加图片'),
        ),
    ]
