# Generated by Django 3.2.7 on 2021-12-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0083_auto_20211119_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=255, verbose_name='达人名称')),
                ('expert_tag', models.CharField(max_length=255, verbose_name='达人标签')),
                ('expert_order', models.CharField(max_length=255, verbose_name='排序')),
                ('expert_introduction', models.TextField(max_length=2048, verbose_name='达人介绍')),
                ('is_book_time', models.CharField(max_length=255, verbose_name='可预约时间')),
                ('book_status', models.CharField(choices=[('0', '可预约'), ('1', '已约满')], default=0, max_length=255, verbose_name='预约状态')),
                ('max_book_num', models.CharField(max_length=255, verbose_name='最大预约人数')),
                ('expert_img', models.ImageField(upload_to='photo', verbose_name='达人封面')),
            ],
        ),
    ]
