# Generated by Django 3.2.7 on 2021-12-13 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0085_auto_20211202_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255, verbose_name='用户姓名')),
                ('u_email', models.CharField(max_length=255, verbose_name='用户邮箱')),
                ('u_context', models.CharField(max_length=255, verbose_name='用户留言内容')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 29, 34, 837544), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 29, 34, 838541), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 29, 34, 834552), verbose_name='创建时间'),
        ),
    ]
