# Generated by Django 3.2.7 on 2021-12-13 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0086_auto_20211213_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 31, 38, 960972), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 31, 38, 961969), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='u_context',
            field=models.CharField(max_length=2000, verbose_name='用户留言内容'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 11, 31, 38, 957980), verbose_name='创建时间'),
        ),
    ]
