# Generated by Django 3.2.7 on 2021-12-20 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0092_auto_20211217_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateTimeField(verbose_name='账单日期')),
                ('income_expenses', models.IntegerField(choices=[], verbose_name='收支')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('income_type', models.IntegerField(choices=[], verbose_name='收入类型')),
                ('spending_type', models.IntegerField(choices=[], verbose_name='支出类型')),
                ('purposes', models.CharField(max_length=255, verbose_name='用途')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 36, 54, 328883), verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 36, 54, 326888), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 36, 54, 326888), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 36, 54, 327887), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 36, 54, 327887), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 36, 54, 324894), verbose_name='创建时间'),
        ),
    ]
