# Generated by Django 3.2.7 on 2021-12-20 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0095_auto_20211220_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 50, 2, 228279), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='income_expenses',
            field=models.CharField(choices=[('0', '收入'), ('1', '支出')], max_length=255, verbose_name='收支'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='income_type',
            field=models.CharField(blank=True, choices=[('0', '薪资'), ('1', '其他')], max_length=255, verbose_name='收入类型'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='spending_type',
            field=models.CharField(blank=True, choices=[('0', '交通'), ('1', '餐饮'), ('2', '红包'), ('3', '娱乐'), ('4', '其他')], max_length=255, verbose_name='支出类型'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 50, 2, 226284), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 50, 2, 226284), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 50, 2, 227281), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 50, 2, 227281), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 11, 50, 2, 224289), verbose_name='创建时间'),
        ),
    ]
