# Generated by Django 3.2.7 on 2021-12-21 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0096_auto_20211220_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=800)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-create_time'], 'verbose_name': '账单', 'verbose_name_plural': '账单'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 53, 30, 793701), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 53, 30, 791707), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 53, 30, 792704), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 53, 30, 792704), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 53, 30, 792704), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 14, 53, 30, 789712), verbose_name='创建时间'),
        ),
    ]
