# Generated by Django 3.2.7 on 2022-01-24 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0101_auto_20220124_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroominfo',
            name='meeting_name',
        ),
        migrations.RemoveField(
            model_name='meetingroominfo',
            name='room_use',
        ),
        migrations.RemoveField(
            model_name='overtimeorleave',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='ShopOrders',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='commodity_type',
        ),
        migrations.DeleteModel(
            name='Talks',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 49, 23, 879896), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 49, 23, 879896), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 49, 23, 880893), verbose_name='创建时间'),
        ),
        migrations.DeleteModel(
            name='MeetingRoom',
        ),
        migrations.DeleteModel(
            name='MeetingRoomInfo',
        ),
        migrations.DeleteModel(
            name='OverTimeOrLeave',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
        migrations.DeleteModel(
            name='ShopTypes',
        ),
    ]
