# Generated by Django 3.2.7 on 2022-02-05 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0102_auto_20220124_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 10, 47, 50, 939682), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 10, 47, 50, 940327), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 10, 47, 50, 941005), verbose_name='创建时间'),
        ),
    ]
