# Generated by Django 3.2.7 on 2022-02-24 08:09

import DjangoUeditor.DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0105_auto_20220205_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=DjangoUeditor.DjangoUeditor.models.UEditorField(verbose_name='富文本内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 16, 9, 14, 106468), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 16, 9, 14, 106468), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 16, 9, 14, 106468), verbose_name='创建时间'),
        ),
    ]
