# Generated by Django 3.2.7 on 2022-02-24 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0106_auto_20220224_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='commer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 18, 2, 32, 544528), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 18, 2, 32, 544528), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 18, 2, 32, 545535), verbose_name='创建时间'),
        ),
    ]
