# Generated by Django 3.2.7 on 2022-02-24 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0107_auto_20220224_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='like_comment',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='点赞评论量'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 18, 22, 29, 231103), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 18, 22, 29, 231103), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leavemessage',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 18, 22, 29, 231103), verbose_name='创建时间'),
        ),
    ]
